from pathlib import Path
from datetime import datetime
from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from abuseipdb_client import get_quick_summary
from config import OUTPUT_DIR, RISK_THRESHOLDS

def get_risk_recommendation(score: int) -> tuple:
    """Return risk level, text, and RGBColor object."""
    if score >= RISK_THRESHOLDS["BLOCK"]:
        return "BLOCK", "BLOCK this IP immediately - High Risk", RGBColor(211, 47, 47)
    elif score >= RISK_THRESHOLDS["INVESTIGATE"]:
        return "INVESTIGATE", "Investigate further - Medium Risk", RGBColor(245, 124, 0)
    else:
        return "LOW_RISK", "Low Risk - Generally safe to allow", RGBColor(56, 142, 60)


def add_risk_box_docx(doc, recommendation_text: str, score: int, color: RGBColor):
    """Create highlighted risk box for DOCX."""
    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.add_run("RISK RECOMMENDATION")
    run.font.size = Pt(16)
    run.font.bold = True
    run.font.color.rgb = color

    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.add_run(recommendation_text)
    run.font.size = Pt(18)
    run.font.bold = True
    run.font.color.rgb = color

    p = doc.add_paragraph()
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER
    run = p.add_run(f"{score}%")
    run.font.size = Pt(48)
    run.font.bold = True
    run.font.color.rgb = color

    p = doc.add_paragraph("Abuse Confidence Score")
    p.alignment = WD_ALIGN_PARAGRAPH.CENTER


def generate_executive_document(data: dict, ip: str):
    """Generate professional DOCX Executive Report (PDF disabled due to WeasyPrint issues)"""
    summary = get_quick_summary(data)
    score = summary.get("abuse_score", 0)
    level, recommendation_text, color = get_risk_recommendation(score)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    scan_date = datetime.now().strftime("%B %d, %Y at %H:%M")

    # ====================== DOCX Generation ======================
    doc = Document()
    style = doc.styles['Normal']
    style.font.name = 'Arial'
    style.font.size = Pt(11)

    # Header
    doc.add_heading("IP Reputation Executive Report", 0).alignment = WD_ALIGN_PARAGRAPH.CENTER
    doc.add_paragraph(f"Generated on {scan_date}").alignment = WD_ALIGN_PARAGRAPH.CENTER
    doc.add_paragraph()

    # Risk Box
    add_risk_box_docx(doc, recommendation_text, score, color)
    doc.add_paragraph()

    # Key Facts Table
    table = doc.add_table(rows=4, cols=2)
    table.style = 'Light Shading Accent 1'
    table.autofit = True

    rows = [
        ("IP Address", ip),
        ("Country", summary.get("country", "N/A")),
        ("ISP / Provider", summary.get("isp", "N/A")),
        ("Usage Type", summary.get("usage_type", "N/A"))
    ]

    for i, (label, value) in enumerate(rows):
        table.cell(i, 0).text = label
        table.cell(i, 0).paragraphs[0].runs[0].font.bold = True
        table.cell(i, 1).text = str(value)

    # Key Findings
    doc.add_heading("Key Findings", level=2)
    for label, value in [
        ("Total Reports", summary.get("total_reports", 0)),
        ("Last Reported", summary.get("last_reported", "N/A")),
        ("Tor / Proxy / VPN", f"{summary.get('is_tor', False)} / {summary.get('is_proxy', False)} / {summary.get('is_vpn', False)}")
    ]:
        p = doc.add_paragraph()
        p.add_run(f"{label}: ").bold = True
        p.add_run(str(value))

    # Recommended Action
    doc.add_heading("Recommended Action", level=2)
    doc.add_paragraph(f"Based on AbuseIPDB data, we recommend {recommendation_text.split(' - ')[0]} this IP address.")

    # Footer
    footer = doc.add_paragraph("This is an automated executive summary generated by IP Reputation Checker.")
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    footer.runs[0].font.size = Pt(9)

    docx_path = OUTPUT_DIR / f"IP_Executive_Report_{ip}_{timestamp}.docx"
    doc.save(docx_path)

    print(f"✅ DOCX Executive Report saved successfully: {docx_path}")
    print("   Note: PDF generation is currently disabled due to system library issue.")

    return docx_path